In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/resume_data.csv", encoding="utf-8-sig")

In [3]:
df.columns = df.columns.str.replace("\ufeff", "", regex=False).str.strip()
df.columns.tolist()

['address',
 'career_objective',
 'skills',
 'educational_institution_name',
 'degree_names',
 'passing_years',
 'educational_results',
 'result_types',
 'major_field_of_studies',
 'professional_company_names',
 'company_urls',
 'start_dates',
 'end_dates',
 'related_skils_in_job',
 'positions',
 'locations',
 'responsibilities',
 'extra_curricular_activity_types',
 'extra_curricular_organization_names',
 'extra_curricular_organization_links',
 'role_positions',
 'languages',
 'proficiency_levels',
 'certification_providers',
 'certification_skills',
 'online_links',
 'issue_dates',
 'expiry_dates',
 'job_position_name',
 'educationaL_requirements',
 'experiencere_requirement',
 'age_requirement',
 'responsibilities.1',
 'skills_required',
 'matched_score']

In [4]:
df = df[["skills_required", "job_position_name"]]
df.head()

,skills_required,job_position_name
0,NaN,Senior Software Engineer
1,NaN,Machine Learning (ML) Engineer
2,Brand Promotion\nCampaign Management\nField Su...,"Executive/ Senior Executive- Trade Marketing, ..."
3,Fast typing skill\nIELTSInternet browsing & on...,Business Development Executive
4,iOS\niOS App Developer\niOS Application Develo...,Senior iOS Engineer

In [5]:
df = df.rename(columns={"skills_required": "skills"})
df.head()

,skills,job_position_name
0,NaN,Senior Software Engineer
1,NaN,Machine Learning (ML) Engineer
2,Brand Promotion\nCampaign Management\nField Su...,"Executive/ Senior Executive- Trade Marketing, ..."
3,Fast typing skill\nIELTSInternet browsing & on...,Business Development Executive
4,iOS\niOS App Developer\niOS Application Develo...,Senior iOS Engineer

In [6]:
df = df.dropna(subset=["skills", "job_position_name"])
df.shape

(7843, 2)

In [7]:
df.head()

,skills,job_position_name
2,Brand Promotion\nCampaign Management\nField Su...,"Executive/ Senior Executive- Trade Marketing, ..."
3,Fast typing skill\nIELTSInternet browsing & on...,Business Development Executive
4,iOS\niOS App Developer\niOS Application Develo...,Senior iOS Engineer
5,Python\nR or Java\nTensorFlow\nPyTorch\nScikit...,AI Engineer
6,iOS\niOS App Developer\niOS Application Develo...,Senior iOS Engineer

In [8]:
import re

def clean_text(text):
    text = str(text)
    text = text.lower()

    # remove URLs
    text = re.sub(r"http\S+", "", text)

    # keep +, #, ., / (important for skills)
    text = re.sub(r"[^a-zA-Z0-9+#./ ]", " ", text)

    # normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [9]:
df["skills"] = df["skills"].apply(clean_text)
df.head()

,skills,job_position_name
2,brand promotion campaign management field supe...,"Executive/ Senior Executive- Trade Marketing, ..."
3,fast typing skill ieltsinternet browsing onlin...,Business Development Executive
4,ios ios app developer ios application developm...,Senior iOS Engineer
5,python r or java tensorflow pytorch scikit learn.,AI Engineer
6,ios ios app developer ios application developm...,Senior iOS Engineer

In [10]:
df = df[df["skills"].str.strip() != ""]
df.shape

(7843, 2)

In [11]:
df.head()

,skills,job_position_name
2,brand promotion campaign management field supe...,"Executive/ Senior Executive- Trade Marketing, ..."
3,fast typing skill ieltsinternet browsing onlin...,Business Development Executive
4,ios ios app developer ios application developm...,Senior iOS Engineer
5,python r or java tensorflow pytorch scikit learn.,AI Engineer
6,ios ios app developer ios application developm...,Senior iOS Engineer

In [12]:
df = df.drop_duplicates()
df.shape

(23, 2)

In [13]:
df.head()

,skills,job_position_name
2,brand promotion campaign management field supe...,"Executive/ Senior Executive- Trade Marketing, ..."
3,fast typing skill ieltsinternet browsing onlin...,Business Development Executive
4,ios ios app developer ios application developm...,Senior iOS Engineer
5,python r or java tensorflow pytorch scikit learn.,AI Engineer
8,maintenance and troubleshooting mechanical,Mechanical Engineer

In [14]:
df.to_csv("clean_skills_dataset.csv", index=False)
print("Clean dataset saved successfully!")

Clean dataset saved successfully!